#!/bin/bash

if [ "$1" == "" ]; then echo "usage: ./gen_rename_patch.pl <in_patch>"; exit -1; fi

OLD="$1.old"
mv $1 $OLD && cat $OLD | \
	sed s,'drivers/media/dvb/b2c2/Kconfig','drivers/media/common/b2c2/Kconfig',g | \
	sed s,'drivers/media/dvb/b2c2/flexcop-common.h','drivers/media/common/b2c2/flexcop-common.h',g | \
	sed s,'drivers/media/dvb/b2c2/flexcop-eeprom.c','drivers/media/common/b2c2/flexcop-eeprom.c',g | \
	sed s,'drivers/media/dvb/b2c2/flexcop-fe-tuner.c','drivers/media/common/b2c2/flexcop-fe-tuner.c',g | \
	sed s,'drivers/media/dvb/b2c2/flexcop-hw-filter.c','drivers/media/common/b2c2/flexcop-hw-filter.c',g | \
	sed s,'drivers/media/dvb/b2c2/flexcop-i2c.c','drivers/media/common/b2c2/flexcop-i2c.c',g | \
	sed s,'drivers/media/dvb/b2c2/flexcop-misc.c','drivers/media/common/b2c2/flexcop-misc.c',g | \
	sed s,'drivers/media/dvb/b2c2/flexcop-reg.h','drivers/media/common/b2c2/flexcop-reg.h',g | \
	sed s,'drivers/media/dvb/b2c2/flexcop-sram.c','drivers/media/common/b2c2/flexcop-sram.c',g | \
	sed s,'drivers/media/dvb/b2c2/flexcop.c','drivers/media/common/b2c2/flexcop.c',g | \
	sed s,'drivers/media/dvb/b2c2/flexcop.h','drivers/media/common/b2c2/flexcop.h',g | \
	sed s,'drivers/media/dvb/b2c2/flexcop_ibi_value_be.h','drivers/media/common/b2c2/flexcop_ibi_value_be.h',g | \
	sed s,'drivers/media/dvb/b2c2/flexcop_ibi_value_le.h','drivers/media/common/b2c2/flexcop_ibi_value_le.h',g | \
	sed s,'drivers/media/common/saa7146_core.c','drivers/media/common/saa7146/saa7146_core.c',g | \
	sed s,'drivers/media/common/saa7146_fops.c','drivers/media/common/saa7146/saa7146_fops.c',g | \
	sed s,'drivers/media/common/saa7146_hlp.c','drivers/media/common/saa7146/saa7146_hlp.c',g | \
	sed s,'drivers/media/common/saa7146_i2c.c','drivers/media/common/saa7146/saa7146_i2c.c',g | \
	sed s,'drivers/media/common/saa7146_vbi.c','drivers/media/common/saa7146/saa7146_vbi.c',g | \
	sed s,'drivers/media/common/saa7146_video.c','drivers/media/common/saa7146/saa7146_video.c',g | \
	sed s,'drivers/media/dvb/siano/Makefile','drivers/media/common/siano/Makefile',g | \
	sed s,'drivers/media/dvb/siano/sms-cards.c','drivers/media/common/siano/sms-cards.c',g | \
	sed s,'drivers/media/dvb/siano/sms-cards.h','drivers/media/common/siano/sms-cards.h',g | \
	sed s,'drivers/media/dvb/siano/smscoreapi.c','drivers/media/common/siano/smscoreapi.c',g | \
	sed s,'drivers/media/dvb/siano/smscoreapi.h','drivers/media/common/siano/smscoreapi.h',g | \
	sed s,'drivers/media/dvb/siano/smsdvb.c','drivers/media/common/siano/smsdvb.c',g | \
	sed s,'drivers/media/dvb/siano/smsendian.c','drivers/media/common/siano/smsendian.c',g | \
	sed s,'drivers/media/dvb/siano/smsendian.h','drivers/media/common/siano/smsendian.h',g | \
	sed s,'drivers/media/dvb/siano/smsir.c','drivers/media/common/siano/smsir.c',g | \
	sed s,'drivers/media/dvb/siano/smsir.h','drivers/media/common/siano/smsir.h',g | \
	sed s,'drivers/media/dvb/dvb-core/Makefile','drivers/media/dvb-core/Makefile',g | \
	sed s,'drivers/media/dvb/dvb-core/demux.h','drivers/media/dvb-core/demux.h',g | \
	sed s,'drivers/media/dvb/dvb-core/dmxdev.c','drivers/media/dvb-core/dmxdev.c',g | \
	sed s,'drivers/media/dvb/dvb-core/dmxdev.h','drivers/media/dvb-core/dmxdev.h',g | \
	sed s,'drivers/media/dvb/dvb-core/dvb-usb-ids.h','drivers/media/dvb-core/dvb-usb-ids.h',g | \
	sed s,'drivers/media/dvb/dvb-core/dvb_ca_en50221.c','drivers/media/dvb-core/dvb_ca_en50221.c',g | \
	sed s,'drivers/media/dvb/dvb-core/dvb_ca_en50221.h','drivers/media/dvb-core/dvb_ca_en50221.h',g | \
	sed s,'drivers/media/dvb/dvb-core/dvb_demux.c','drivers/media/dvb-core/dvb_demux.c',g | \
	sed s,'drivers/media/dvb/dvb-core/dvb_demux.h','drivers/media/dvb-core/dvb_demux.h',g | \
	sed s,'drivers/media/dvb/dvb-core/dvb_filter.c','drivers/media/dvb-core/dvb_filter.c',g | \
	sed s,'drivers/media/dvb/dvb-core/dvb_filter.h','drivers/media/dvb-core/dvb_filter.h',g | \
	sed s,'drivers/media/dvb/dvb-core/dvb_frontend.c','drivers/media/dvb-core/dvb_frontend.c',g | \
	sed s,'drivers/media/dvb/dvb-core/dvb_frontend.h','drivers/media/dvb-core/dvb_frontend.h',g | \
	sed s,'drivers/media/dvb/dvb-core/dvb_math.c','drivers/media/dvb-core/dvb_math.c',g | \
	sed s,'drivers/media/dvb/dvb-core/dvb_math.h','drivers/media/dvb-core/dvb_math.h',g | \
	sed s,'drivers/media/dvb/dvb-core/dvb_net.c','drivers/media/dvb-core/dvb_net.c',g | \
	sed s,'drivers/media/dvb/dvb-core/dvb_net.h','drivers/media/dvb-core/dvb_net.h',g | \
	sed s,'drivers/media/dvb/dvb-core/dvb_ringbuffer.c','drivers/media/dvb-core/dvb_ringbuffer.c',g | \
	sed s,'drivers/media/dvb/dvb-core/dvb_ringbuffer.h','drivers/media/dvb-core/dvb_ringbuffer.h',g | \
	sed s,'drivers/media/dvb/dvb-core/dvbdev.c','drivers/media/dvb-core/dvbdev.c',g | \
	sed s,'drivers/media/dvb/dvb-core/dvbdev.h','drivers/media/dvb-core/dvbdev.h',g | \
	sed s,'drivers/media/dvb/frontends/Kconfig','drivers/media/dvb-frontends/Kconfig',g | \
	sed s,'drivers/media/dvb/frontends/Makefile','drivers/media/dvb-frontends/Makefile',g | \
	sed s,'drivers/media/dvb/frontends/a8293.c','drivers/media/dvb-frontends/a8293.c',g | \
	sed s,'drivers/media/dvb/frontends/a8293.h','drivers/media/dvb-frontends/a8293.h',g | \
	sed s,'drivers/media/dvb/frontends/af9013.c','drivers/media/dvb-frontends/af9013.c',g | \
	sed s,'drivers/media/dvb/frontends/af9013.h','drivers/media/dvb-frontends/af9013.h',g | \
	sed s,'drivers/media/dvb/frontends/af9013_priv.h','drivers/media/dvb-frontends/af9013_priv.h',g | \
	sed s,'drivers/media/dvb/frontends/af9033.c','drivers/media/dvb-frontends/af9033.c',g | \
	sed s,'drivers/media/dvb/frontends/af9033.h','drivers/media/dvb-frontends/af9033.h',g | \
	sed s,'drivers/media/dvb/frontends/af9033_priv.h','drivers/media/dvb-frontends/af9033_priv.h',g | \
	sed s,'drivers/media/dvb/frontends/atbm8830.c','drivers/media/dvb-frontends/atbm8830.c',g | \
	sed s,'drivers/media/dvb/frontends/atbm8830.h','drivers/media/dvb-frontends/atbm8830.h',g | \
	sed s,'drivers/media/dvb/frontends/atbm8830_priv.h','drivers/media/dvb-frontends/atbm8830_priv.h',g | \
	sed s,'drivers/media/dvb/frontends/au8522.h','drivers/media/dvb-frontends/au8522.h',g | \
	sed s,'drivers/media/dvb/frontends/au8522_common.c','drivers/media/dvb-frontends/au8522_common.c',g | \
	sed s,'drivers/media/dvb/frontends/au8522_decoder.c','drivers/media/dvb-frontends/au8522_decoder.c',g | \
	sed s,'drivers/media/dvb/frontends/au8522_dig.c','drivers/media/dvb-frontends/au8522_dig.c',g | \
	sed s,'drivers/media/dvb/frontends/au8522_priv.h','drivers/media/dvb-frontends/au8522_priv.h',g | \
	sed s,'drivers/media/dvb/frontends/bcm3510.c','drivers/media/dvb-frontends/bcm3510.c',g | \
	sed s,'drivers/media/dvb/frontends/bcm3510.h','drivers/media/dvb-frontends/bcm3510.h',g | \
	sed s,'drivers/media/dvb/frontends/bcm3510_priv.h','drivers/media/dvb-frontends/bcm3510_priv.h',g | \
	sed s,'drivers/media/dvb/frontends/bsbe1-d01a.h','drivers/media/dvb-frontends/bsbe1-d01a.h',g | \
	sed s,'drivers/media/dvb/frontends/bsbe1.h','drivers/media/dvb-frontends/bsbe1.h',g | \
	sed s,'drivers/media/dvb/frontends/bsru6.h','drivers/media/dvb-frontends/bsru6.h',g | \
	sed s,'drivers/media/dvb/frontends/cx22700.c','drivers/media/dvb-frontends/cx22700.c',g | \
	sed s,'drivers/media/dvb/frontends/cx22700.h','drivers/media/dvb-frontends/cx22700.h',g | \
	sed s,'drivers/media/dvb/frontends/cx22702.c','drivers/media/dvb-frontends/cx22702.c',g | \
	sed s,'drivers/media/dvb/frontends/cx22702.h','drivers/media/dvb-frontends/cx22702.h',g | \
	sed s,'drivers/media/dvb/frontends/cx24110.c','drivers/media/dvb-frontends/cx24110.c',g | \
	sed s,'drivers/media/dvb/frontends/cx24110.h','drivers/media/dvb-frontends/cx24110.h',g | \
	sed s,'drivers/media/dvb/frontends/cx24113.c','drivers/media/dvb-frontends/cx24113.c',g | \
	sed s,'drivers/media/dvb/frontends/cx24113.h','drivers/media/dvb-frontends/cx24113.h',g | \
	sed s,'drivers/media/dvb/frontends/cx24116.c','drivers/media/dvb-frontends/cx24116.c',g | \
	sed s,'drivers/media/dvb/frontends/cx24116.h','drivers/media/dvb-frontends/cx24116.h',g | \
	sed s,'drivers/media/dvb/frontends/cx24123.c','drivers/media/dvb-frontends/cx24123.c',g | \
	sed s,'drivers/media/dvb/frontends/cx24123.h','drivers/media/dvb-frontends/cx24123.h',g | \
	sed s,'drivers/media/dvb/frontends/cxd2820r.h','drivers/media/dvb-frontends/cxd2820r.h',g | \
	sed s,'drivers/media/dvb/frontends/cxd2820r_c.c','drivers/media/dvb-frontends/cxd2820r_c.c',g | \
	sed s,'drivers/media/dvb/frontends/cxd2820r_core.c','drivers/media/dvb-frontends/cxd2820r_core.c',g | \
	sed s,'drivers/media/dvb/frontends/cxd2820r_priv.h','drivers/media/dvb-frontends/cxd2820r_priv.h',g | \
	sed s,'drivers/media/dvb/frontends/cxd2820r_t.c','drivers/media/dvb-frontends/cxd2820r_t.c',g | \
	sed s,'drivers/media/dvb/frontends/cxd2820r_t2.c','drivers/media/dvb-frontends/cxd2820r_t2.c',g | \
	sed s,'drivers/media/dvb/frontends/dib0070.c','drivers/media/dvb-frontends/dib0070.c',g | \
	sed s,'drivers/media/dvb/frontends/dib0070.h','drivers/media/dvb-frontends/dib0070.h',g | \
	sed s,'drivers/media/dvb/frontends/dib0090.c','drivers/media/dvb-frontends/dib0090.c',g | \
	sed s,'drivers/media/dvb/frontends/dib0090.h','drivers/media/dvb-frontends/dib0090.h',g | \
	sed s,'drivers/media/dvb/frontends/dib3000.h','drivers/media/dvb-frontends/dib3000.h',g | \
	sed s,'drivers/media/dvb/frontends/dib3000mb.c','drivers/media/dvb-frontends/dib3000mb.c',g | \
	sed s,'drivers/media/dvb/frontends/dib3000mb_priv.h','drivers/media/dvb-frontends/dib3000mb_priv.h',g | \
	sed s,'drivers/media/dvb/frontends/dib3000mc.c','drivers/media/dvb-frontends/dib3000mc.c',g | \
	sed s,'drivers/media/dvb/frontends/dib3000mc.h','drivers/media/dvb-frontends/dib3000mc.h',g | \
	sed s,'drivers/media/dvb/frontends/dib7000m.c','drivers/media/dvb-frontends/dib7000m.c',g | \
	sed s,'drivers/media/dvb/frontends/dib7000m.h','drivers/media/dvb-frontends/dib7000m.h',g | \
	sed s,'drivers/media/dvb/frontends/dib7000p.c','drivers/media/dvb-frontends/dib7000p.c',g | \
	sed s,'drivers/media/dvb/frontends/dib7000p.h','drivers/media/dvb-frontends/dib7000p.h',g | \
	sed s,'drivers/media/dvb/frontends/dib8000.c','drivers/media/dvb-frontends/dib8000.c',g | \
	sed s,'drivers/media/dvb/frontends/dib8000.h','drivers/media/dvb-frontends/dib8000.h',g | \
	sed s,'drivers/media/dvb/frontends/dib9000.c','drivers/media/dvb-frontends/dib9000.c',g | \
	sed s,'drivers/media/dvb/frontends/dib9000.h','drivers/media/dvb-frontends/dib9000.h',g | \
	sed s,'drivers/media/dvb/frontends/dibx000_common.c','drivers/media/dvb-frontends/dibx000_common.c',g | \
	sed s,'drivers/media/dvb/frontends/dibx000_common.h','drivers/media/dvb-frontends/dibx000_common.h',g | \
	sed s,'drivers/media/dvb/frontends/drxd.h','drivers/media/dvb-frontends/drxd.h',g | \
	sed s,'drivers/media/dvb/frontends/drxd_firm.c','drivers/media/dvb-frontends/drxd_firm.c',g | \
	sed s,'drivers/media/dvb/frontends/drxd_firm.h','drivers/media/dvb-frontends/drxd_firm.h',g | \
	sed s,'drivers/media/dvb/frontends/drxd_hard.c','drivers/media/dvb-frontends/drxd_hard.c',g | \
	sed s,'drivers/media/dvb/frontends/drxd_map_firm.h','drivers/media/dvb-frontends/drxd_map_firm.h',g | \
	sed s,'drivers/media/dvb/frontends/drxk.h','drivers/media/dvb-frontends/drxk.h',g | \
	sed s,'drivers/media/dvb/frontends/drxk_hard.c','drivers/media/dvb-frontends/drxk_hard.c',g | \
	sed s,'drivers/media/dvb/frontends/drxk_hard.h','drivers/media/dvb-frontends/drxk_hard.h',g | \
	sed s,'drivers/media/dvb/frontends/drxk_map.h','drivers/media/dvb-frontends/drxk_map.h',g | \
	sed s,'drivers/media/dvb/frontends/ds3000.c','drivers/media/dvb-frontends/ds3000.c',g | \
	sed s,'drivers/media/dvb/frontends/ds3000.h','drivers/media/dvb-frontends/ds3000.h',g | \
	sed s,'drivers/media/dvb/frontends/dvb-pll.c','drivers/media/dvb-frontends/dvb-pll.c',g | \
	sed s,'drivers/media/dvb/frontends/dvb-pll.h','drivers/media/dvb-frontends/dvb-pll.h',g | \
	sed s,'drivers/media/dvb/frontends/dvb_dummy_fe.c','drivers/media/dvb-frontends/dvb_dummy_fe.c',g | \
	sed s,'drivers/media/dvb/frontends/dvb_dummy_fe.h','drivers/media/dvb-frontends/dvb_dummy_fe.h',g | \
	sed s,'drivers/media/dvb/frontends/ec100.c','drivers/media/dvb-frontends/ec100.c',g | \
	sed s,'drivers/media/dvb/frontends/ec100.h','drivers/media/dvb-frontends/ec100.h',g | \
	sed s,'drivers/media/dvb/frontends/ec100_priv.h','drivers/media/dvb-frontends/ec100_priv.h',g | \
	sed s,'drivers/media/dvb/frontends/eds1547.h','drivers/media/dvb-frontends/eds1547.h',g | \
	sed s,'drivers/media/dvb/frontends/hd29l2.c','drivers/media/dvb-frontends/hd29l2.c',g | \
	sed s,'drivers/media/dvb/frontends/hd29l2.h','drivers/media/dvb-frontends/hd29l2.h',g | \
	sed s,'drivers/media/dvb/frontends/hd29l2_priv.h','drivers/media/dvb-frontends/hd29l2_priv.h',g | \
	sed s,'drivers/media/dvb/frontends/isl6405.c','drivers/media/dvb-frontends/isl6405.c',g | \
	sed s,'drivers/media/dvb/frontends/isl6405.h','drivers/media/dvb-frontends/isl6405.h',g | \
	sed s,'drivers/media/dvb/frontends/isl6421.c','drivers/media/dvb-frontends/isl6421.c',g | \
	sed s,'drivers/media/dvb/frontends/isl6421.h','drivers/media/dvb-frontends/isl6421.h',g | \
	sed s,'drivers/media/dvb/frontends/isl6423.c','drivers/media/dvb-frontends/isl6423.c',g | \
	sed s,'drivers/media/dvb/frontends/isl6423.h','drivers/media/dvb-frontends/isl6423.h',g | \
	sed s,'drivers/media/dvb/frontends/it913x-fe-priv.h','drivers/media/dvb-frontends/it913x-fe-priv.h',g | \
	sed s,'drivers/media/dvb/frontends/it913x-fe.c','drivers/media/dvb-frontends/it913x-fe.c',g | \
	sed s,'drivers/media/dvb/frontends/it913x-fe.h','drivers/media/dvb-frontends/it913x-fe.h',g | \
	sed s,'drivers/media/dvb/frontends/itd1000.c','drivers/media/dvb-frontends/itd1000.c',g | \
	sed s,'drivers/media/dvb/frontends/itd1000.h','drivers/media/dvb-frontends/itd1000.h',g | \
	sed s,'drivers/media/dvb/frontends/itd1000_priv.h','drivers/media/dvb-frontends/itd1000_priv.h',g | \
	sed s,'drivers/media/dvb/frontends/ix2505v.c','drivers/media/dvb-frontends/ix2505v.c',g | \
	sed s,'drivers/media/dvb/frontends/ix2505v.h','drivers/media/dvb-frontends/ix2505v.h',g | \
	sed s,'drivers/media/dvb/frontends/l64781.c','drivers/media/dvb-frontends/l64781.c',g | \
	sed s,'drivers/media/dvb/frontends/l64781.h','drivers/media/dvb-frontends/l64781.h',g | \
	sed s,'drivers/media/dvb/frontends/lg2160.c','drivers/media/dvb-frontends/lg2160.c',g | \
	sed s,'drivers/media/dvb/frontends/lg2160.h','drivers/media/dvb-frontends/lg2160.h',g | \
	sed s,'drivers/media/dvb/frontends/lgdt3305.c','drivers/media/dvb-frontends/lgdt3305.c',g | \
	sed s,'drivers/media/dvb/frontends/lgdt3305.h','drivers/media/dvb-frontends/lgdt3305.h',g | \
	sed s,'drivers/media/dvb/frontends/lgdt330x.c','drivers/media/dvb-frontends/lgdt330x.c',g | \
	sed s,'drivers/media/dvb/frontends/lgdt330x.h','drivers/media/dvb-frontends/lgdt330x.h',g | \
	sed s,'drivers/media/dvb/frontends/lgdt330x_priv.h','drivers/media/dvb-frontends/lgdt330x_priv.h',g | \
	sed s,'drivers/media/dvb/frontends/lgs8gl5.c','drivers/media/dvb-frontends/lgs8gl5.c',g | \
	sed s,'drivers/media/dvb/frontends/lgs8gl5.h','drivers/media/dvb-frontends/lgs8gl5.h',g | \
	sed s,'drivers/media/dvb/frontends/lgs8gxx.c','drivers/media/dvb-frontends/lgs8gxx.c',g | \
	sed s,'drivers/media/dvb/frontends/lgs8gxx.h','drivers/media/dvb-frontends/lgs8gxx.h',g | \
	sed s,'drivers/media/dvb/frontends/lgs8gxx_priv.h','drivers/media/dvb-frontends/lgs8gxx_priv.h',g | \
	sed s,'drivers/media/dvb/frontends/lnbh24.h','drivers/media/dvb-frontends/lnbh24.h',g | \
	sed s,'drivers/media/dvb/frontends/lnbp21.c','drivers/media/dvb-frontends/lnbp21.c',g | \
	sed s,'drivers/media/dvb/frontends/lnbp21.h','drivers/media/dvb-frontends/lnbp21.h',g | \
	sed s,'drivers/media/dvb/frontends/lnbp22.c','drivers/media/dvb-frontends/lnbp22.c',g | \
	sed s,'drivers/media/dvb/frontends/lnbp22.h','drivers/media/dvb-frontends/lnbp22.h',g | \
	sed s,'drivers/media/dvb/frontends/m88rs2000.c','drivers/media/dvb-frontends/m88rs2000.c',g | \
	sed s,'drivers/media/dvb/frontends/m88rs2000.h','drivers/media/dvb-frontends/m88rs2000.h',g | \
	sed s,'drivers/media/dvb/frontends/mb86a16.c','drivers/media/dvb-frontends/mb86a16.c',g | \
	sed s,'drivers/media/dvb/frontends/mb86a16.h','drivers/media/dvb-frontends/mb86a16.h',g | \
	sed s,'drivers/media/dvb/frontends/mb86a16_priv.h','drivers/media/dvb-frontends/mb86a16_priv.h',g | \
	sed s,'drivers/media/dvb/frontends/mb86a20s.c','drivers/media/dvb-frontends/mb86a20s.c',g | \
	sed s,'drivers/media/dvb/frontends/mb86a20s.h','drivers/media/dvb-frontends/mb86a20s.h',g | \
	sed s,'drivers/media/dvb/frontends/mt312.c','drivers/media/dvb-frontends/mt312.c',g | \
	sed s,'drivers/media/dvb/frontends/mt312.h','drivers/media/dvb-frontends/mt312.h',g | \
	sed s,'drivers/media/dvb/frontends/mt312_priv.h','drivers/media/dvb-frontends/mt312_priv.h',g | \
	sed s,'drivers/media/dvb/frontends/mt352.c','drivers/media/dvb-frontends/mt352.c',g | \
	sed s,'drivers/media/dvb/frontends/mt352.h','drivers/media/dvb-frontends/mt352.h',g | \
	sed s,'drivers/media/dvb/frontends/mt352_priv.h','drivers/media/dvb-frontends/mt352_priv.h',g | \
	sed s,'drivers/media/dvb/frontends/nxt200x.c','drivers/media/dvb-frontends/nxt200x.c',g | \
	sed s,'drivers/media/dvb/frontends/nxt200x.h','drivers/media/dvb-frontends/nxt200x.h',g | \
	sed s,'drivers/media/dvb/frontends/nxt6000.c','drivers/media/dvb-frontends/nxt6000.c',g | \
	sed s,'drivers/media/dvb/frontends/nxt6000.h','drivers/media/dvb-frontends/nxt6000.h',g | \
	sed s,'drivers/media/dvb/frontends/nxt6000_priv.h','drivers/media/dvb-frontends/nxt6000_priv.h',g | \
	sed s,'drivers/media/dvb/frontends/or51132.c','drivers/media/dvb-frontends/or51132.c',g | \
	sed s,'drivers/media/dvb/frontends/or51132.h','drivers/media/dvb-frontends/or51132.h',g | \
	sed s,'drivers/media/dvb/frontends/or51211.c','drivers/media/dvb-frontends/or51211.c',g | \
	sed s,'drivers/media/dvb/frontends/or51211.h','drivers/media/dvb-frontends/or51211.h',g | \
	sed s,'drivers/media/dvb/frontends/rtl2830.c','drivers/media/dvb-frontends/rtl2830.c',g | \
	sed s,'drivers/media/dvb/frontends/rtl2830.h','drivers/media/dvb-frontends/rtl2830.h',g | \
	sed s,'drivers/media/dvb/frontends/rtl2830_priv.h','drivers/media/dvb-frontends/rtl2830_priv.h',g | \
	sed s,'drivers/media/dvb/frontends/rtl2832.c','drivers/media/dvb-frontends/rtl2832.c',g | \
	sed s,'drivers/media/dvb/frontends/rtl2832.h','drivers/media/dvb-frontends/rtl2832.h',g | \
	sed s,'drivers/media/dvb/frontends/rtl2832_priv.h','drivers/media/dvb-frontends/rtl2832_priv.h',g | \
	sed s,'drivers/media/dvb/frontends/s5h1409.c','drivers/media/dvb-frontends/s5h1409.c',g | \
	sed s,'drivers/media/dvb/frontends/s5h1409.h','drivers/media/dvb-frontends/s5h1409.h',g | \
	sed s,'drivers/media/dvb/frontends/s5h1411.c','drivers/media/dvb-frontends/s5h1411.c',g | \
	sed s,'drivers/media/dvb/frontends/s5h1411.h','drivers/media/dvb-frontends/s5h1411.h',g | \
	sed s,'drivers/media/dvb/frontends/s5h1420.c','drivers/media/dvb-frontends/s5h1420.c',g | \
	sed s,'drivers/media/dvb/frontends/s5h1420.h','drivers/media/dvb-frontends/s5h1420.h',g | \
	sed s,'drivers/media/dvb/frontends/s5h1420_priv.h','drivers/media/dvb-frontends/s5h1420_priv.h',g | \
	sed s,'drivers/media/dvb/frontends/s5h1432.c','drivers/media/dvb-frontends/s5h1432.c',g | \
	sed s,'drivers/media/dvb/frontends/s5h1432.h','drivers/media/dvb-frontends/s5h1432.h',g | \
	sed s,'drivers/media/dvb/frontends/s921.c','drivers/media/dvb-frontends/s921.c',g | \
	sed s,'drivers/media/dvb/frontends/s921.h','drivers/media/dvb-frontends/s921.h',g | \
	sed s,'drivers/media/dvb/frontends/si21xx.c','drivers/media/dvb-frontends/si21xx.c',g | \
	sed s,'drivers/media/dvb/frontends/si21xx.h','drivers/media/dvb-frontends/si21xx.h',g | \
	sed s,'drivers/media/dvb/frontends/sp8870.c','drivers/media/dvb-frontends/sp8870.c',g | \
	sed s,'drivers/media/dvb/frontends/sp8870.h','drivers/media/dvb-frontends/sp8870.h',g | \
	sed s,'drivers/media/dvb/frontends/sp887x.c','drivers/media/dvb-frontends/sp887x.c',g | \
	sed s,'drivers/media/dvb/frontends/sp887x.h','drivers/media/dvb-frontends/sp887x.h',g | \
	sed s,'drivers/media/dvb/frontends/stb0899_algo.c','drivers/media/dvb-frontends/stb0899_algo.c',g | \
	sed s,'drivers/media/dvb/frontends/stb0899_cfg.h','drivers/media/dvb-frontends/stb0899_cfg.h',g | \
	sed s,'drivers/media/dvb/frontends/stb0899_drv.c','drivers/media/dvb-frontends/stb0899_drv.c',g | \
	sed s,'drivers/media/dvb/frontends/stb0899_drv.h','drivers/media/dvb-frontends/stb0899_drv.h',g | \
	sed s,'drivers/media/dvb/frontends/stb0899_priv.h','drivers/media/dvb-frontends/stb0899_priv.h',g | \
	sed s,'drivers/media/dvb/frontends/stb0899_reg.h','drivers/media/dvb-frontends/stb0899_reg.h',g | \
	sed s,'drivers/media/dvb/frontends/stb6000.c','drivers/media/dvb-frontends/stb6000.c',g | \
	sed s,'drivers/media/dvb/frontends/stb6000.h','drivers/media/dvb-frontends/stb6000.h',g | \
	sed s,'drivers/media/dvb/frontends/stb6100.c','drivers/media/dvb-frontends/stb6100.c',g | \
	sed s,'drivers/media/dvb/frontends/stb6100.h','drivers/media/dvb-frontends/stb6100.h',g | \
	sed s,'drivers/media/dvb/frontends/stb6100_cfg.h','drivers/media/dvb-frontends/stb6100_cfg.h',g | \
	sed s,'drivers/media/dvb/frontends/stb6100_proc.h','drivers/media/dvb-frontends/stb6100_proc.h',g | \
	sed s,'drivers/media/dvb/frontends/stv0288.c','drivers/media/dvb-frontends/stv0288.c',g | \
	sed s,'drivers/media/dvb/frontends/stv0288.h','drivers/media/dvb-frontends/stv0288.h',g | \
	sed s,'drivers/media/dvb/frontends/stv0297.c','drivers/media/dvb-frontends/stv0297.c',g | \
	sed s,'drivers/media/dvb/frontends/stv0297.h','drivers/media/dvb-frontends/stv0297.h',g | \
	sed s,'drivers/media/dvb/frontends/stv0299.c','drivers/media/dvb-frontends/stv0299.c',g | \
	sed s,'drivers/media/dvb/frontends/stv0299.h','drivers/media/dvb-frontends/stv0299.h',g | \
	sed s,'drivers/media/dvb/frontends/stv0367.c','drivers/media/dvb-frontends/stv0367.c',g | \
	sed s,'drivers/media/dvb/frontends/stv0367.h','drivers/media/dvb-frontends/stv0367.h',g | \
	sed s,'drivers/media/dvb/frontends/stv0367_priv.h','drivers/media/dvb-frontends/stv0367_priv.h',g | \
	sed s,'drivers/media/dvb/frontends/stv0367_regs.h','drivers/media/dvb-frontends/stv0367_regs.h',g | \
	sed s,'drivers/media/dvb/frontends/stv0900.h','drivers/media/dvb-frontends/stv0900.h',g | \
	sed s,'drivers/media/dvb/frontends/stv0900_core.c','drivers/media/dvb-frontends/stv0900_core.c',g | \
	sed s,'drivers/media/dvb/frontends/stv0900_init.h','drivers/media/dvb-frontends/stv0900_init.h',g | \
	sed s,'drivers/media/dvb/frontends/stv0900_priv.h','drivers/media/dvb-frontends/stv0900_priv.h',g | \
	sed s,'drivers/media/dvb/frontends/stv0900_reg.h','drivers/media/dvb-frontends/stv0900_reg.h',g | \
	sed s,'drivers/media/dvb/frontends/stv0900_sw.c','drivers/media/dvb-frontends/stv0900_sw.c',g | \
	sed s,'drivers/media/dvb/frontends/stv090x.c','drivers/media/dvb-frontends/stv090x.c',g | \
	sed s,'drivers/media/dvb/frontends/stv090x.h','drivers/media/dvb-frontends/stv090x.h',g | \
	sed s,'drivers/media/dvb/frontends/stv090x_priv.h','drivers/media/dvb-frontends/stv090x_priv.h',g | \
	sed s,'drivers/media/dvb/frontends/stv090x_reg.h','drivers/media/dvb-frontends/stv090x_reg.h',g | \
	sed s,'drivers/media/dvb/frontends/stv6110.c','drivers/media/dvb-frontends/stv6110.c',g | \
	sed s,'drivers/media/dvb/frontends/stv6110.h','drivers/media/dvb-frontends/stv6110.h',g | \
	sed s,'drivers/media/dvb/frontends/stv6110x.c','drivers/media/dvb-frontends/stv6110x.c',g | \
	sed s,'drivers/media/dvb/frontends/stv6110x.h','drivers/media/dvb-frontends/stv6110x.h',g | \
	sed s,'drivers/media/dvb/frontends/stv6110x_priv.h','drivers/media/dvb-frontends/stv6110x_priv.h',g | \
	sed s,'drivers/media/dvb/frontends/stv6110x_reg.h','drivers/media/dvb-frontends/stv6110x_reg.h',g | \
	sed s,'drivers/media/dvb/frontends/tda10021.c','drivers/media/dvb-frontends/tda10021.c',g | \
	sed s,'drivers/media/dvb/frontends/tda10023.c','drivers/media/dvb-frontends/tda10023.c',g | \
	sed s,'drivers/media/dvb/frontends/tda1002x.h','drivers/media/dvb-frontends/tda1002x.h',g | \
	sed s,'drivers/media/dvb/frontends/tda10048.c','drivers/media/dvb-frontends/tda10048.c',g | \
	sed s,'drivers/media/dvb/frontends/tda10048.h','drivers/media/dvb-frontends/tda10048.h',g | \
	sed s,'drivers/media/dvb/frontends/tda1004x.c','drivers/media/dvb-frontends/tda1004x.c',g | \
	sed s,'drivers/media/dvb/frontends/tda1004x.h','drivers/media/dvb-frontends/tda1004x.h',g | \
	sed s,'drivers/media/dvb/frontends/tda10071.c','drivers/media/dvb-frontends/tda10071.c',g | \
	sed s,'drivers/media/dvb/frontends/tda10071.h','drivers/media/dvb-frontends/tda10071.h',g | \
	sed s,'drivers/media/dvb/frontends/tda10071_priv.h','drivers/media/dvb-frontends/tda10071_priv.h',g | \
	sed s,'drivers/media/dvb/frontends/tda10086.c','drivers/media/dvb-frontends/tda10086.c',g | \
	sed s,'drivers/media/dvb/frontends/tda10086.h','drivers/media/dvb-frontends/tda10086.h',g | \
	sed s,'drivers/media/dvb/frontends/tda18271c2dd.c','drivers/media/dvb-frontends/tda18271c2dd.c',g | \
	sed s,'drivers/media/dvb/frontends/tda18271c2dd.h','drivers/media/dvb-frontends/tda18271c2dd.h',g | \
	sed s,'drivers/media/dvb/frontends/tda18271c2dd_maps.h','drivers/media/dvb-frontends/tda18271c2dd_maps.h',g | \
	sed s,'drivers/media/dvb/frontends/tda665x.c','drivers/media/dvb-frontends/tda665x.c',g | \
	sed s,'drivers/media/dvb/frontends/tda665x.h','drivers/media/dvb-frontends/tda665x.h',g | \
	sed s,'drivers/media/dvb/frontends/tda8083.c','drivers/media/dvb-frontends/tda8083.c',g | \
	sed s,'drivers/media/dvb/frontends/tda8083.h','drivers/media/dvb-frontends/tda8083.h',g | \
	sed s,'drivers/media/dvb/frontends/tda8261.c','drivers/media/dvb-frontends/tda8261.c',g | \
	sed s,'drivers/media/dvb/frontends/tda8261.h','drivers/media/dvb-frontends/tda8261.h',g | \
	sed s,'drivers/media/dvb/frontends/tda8261_cfg.h','drivers/media/dvb-frontends/tda8261_cfg.h',g | \
	sed s,'drivers/media/dvb/frontends/tda826x.c','drivers/media/dvb-frontends/tda826x.c',g | \
	sed s,'drivers/media/dvb/frontends/tda826x.h','drivers/media/dvb-frontends/tda826x.h',g | \
	sed s,'drivers/media/dvb/frontends/tdhd1.h','drivers/media/dvb-frontends/tdhd1.h',g | \
	sed s,'drivers/media/dvb/frontends/tua6100.c','drivers/media/dvb-frontends/tua6100.c',g | \
	sed s,'drivers/media/dvb/frontends/tua6100.h','drivers/media/dvb-frontends/tua6100.h',g | \
	sed s,'drivers/media/dvb/frontends/ves1820.c','drivers/media/dvb-frontends/ves1820.c',g | \
	sed s,'drivers/media/dvb/frontends/ves1820.h','drivers/media/dvb-frontends/ves1820.h',g | \
	sed s,'drivers/media/dvb/frontends/ves1x93.c','drivers/media/dvb-frontends/ves1x93.c',g | \
	sed s,'drivers/media/dvb/frontends/ves1x93.h','drivers/media/dvb-frontends/ves1x93.h',g | \
	sed s,'drivers/media/dvb/frontends/z0194a.h','drivers/media/dvb-frontends/z0194a.h',g | \
	sed s,'drivers/media/dvb/frontends/zl10036.c','drivers/media/dvb-frontends/zl10036.c',g | \
	sed s,'drivers/media/dvb/frontends/zl10036.h','drivers/media/dvb-frontends/zl10036.h',g | \
	sed s,'drivers/media/dvb/frontends/zl10039.c','drivers/media/dvb-frontends/zl10039.c',g | \
	sed s,'drivers/media/dvb/frontends/zl10039.h','drivers/media/dvb-frontends/zl10039.h',g | \
	sed s,'drivers/media/dvb/frontends/zl10353.c','drivers/media/dvb-frontends/zl10353.c',g | \
	sed s,'drivers/media/dvb/frontends/zl10353.h','drivers/media/dvb-frontends/zl10353.h',g | \
	sed s,'drivers/media/dvb/frontends/zl10353_priv.h','drivers/media/dvb-frontends/zl10353_priv.h',g | \
	sed s,'drivers/media/dvb/firewire/Kconfig','drivers/media/firewire/Kconfig',g | \
	sed s,'drivers/media/dvb/firewire/Makefile','drivers/media/firewire/Makefile',g | \
	sed s,'drivers/media/dvb/firewire/firedtv-avc.c','drivers/media/firewire/firedtv-avc.c',g | \
	sed s,'drivers/media/dvb/firewire/firedtv-ci.c','drivers/media/firewire/firedtv-ci.c',g | \
	sed s,'drivers/media/dvb/firewire/firedtv-dvb.c','drivers/media/firewire/firedtv-dvb.c',g | \
	sed s,'drivers/media/dvb/firewire/firedtv-fe.c','drivers/media/firewire/firedtv-fe.c',g | \
	sed s,'drivers/media/dvb/firewire/firedtv-fw.c','drivers/media/firewire/firedtv-fw.c',g | \
	sed s,'drivers/media/dvb/firewire/firedtv-rc.c','drivers/media/firewire/firedtv-rc.c',g | \
	sed s,'drivers/media/dvb/firewire/firedtv.h','drivers/media/firewire/firedtv.h',g | \
	sed s,'drivers/media/dvb/siano/smssdio.c','drivers/media/mmc/siano/smssdio.c',g | \
	sed s,'drivers/media/dvb/b2c2/flexcop-dma.c','drivers/media/pci/b2c2/flexcop-dma.c',g | \
	sed s,'drivers/media/dvb/b2c2/flexcop-pci.c','drivers/media/pci/b2c2/flexcop-pci.c',g | \
	sed s,'drivers/media/dvb/bt8xx/Kconfig','drivers/media/pci/bt8xx/Kconfig',g | \
	sed s,'drivers/media/dvb/bt8xx/bt878.c','drivers/media/pci/bt8xx/bt878.c',g | \
	sed s,'drivers/media/dvb/bt8xx/bt878.h','drivers/media/pci/bt8xx/bt878.h',g | \
	sed s,'drivers/media/dvb/bt8xx/dst.c','drivers/media/pci/bt8xx/dst.c',g | \
	sed s,'drivers/media/dvb/bt8xx/dst_ca.c','drivers/media/pci/bt8xx/dst_ca.c',g | \
	sed s,'drivers/media/dvb/bt8xx/dst_ca.h','drivers/media/pci/bt8xx/dst_ca.h',g | \
	sed s,'drivers/media/dvb/bt8xx/dst_common.h','drivers/media/pci/bt8xx/dst_common.h',g | \
	sed s,'drivers/media/dvb/bt8xx/dst_priv.h','drivers/media/pci/bt8xx/dst_priv.h',g | \
	sed s,'drivers/media/dvb/bt8xx/dvb-bt8xx.c','drivers/media/pci/bt8xx/dvb-bt8xx.c',g | \
	sed s,'drivers/media/dvb/bt8xx/dvb-bt8xx.h','drivers/media/pci/bt8xx/dvb-bt8xx.h',g | \
	sed s,'drivers/media/dvb/ddbridge/Kconfig','drivers/media/pci/ddbridge/Kconfig',g | \
	sed s,'drivers/media/dvb/ddbridge/Makefile','drivers/media/pci/ddbridge/Makefile',g | \
	sed s,'drivers/media/dvb/ddbridge/ddbridge-core.c','drivers/media/pci/ddbridge/ddbridge-core.c',g | \
	sed s,'drivers/media/dvb/ddbridge/ddbridge-regs.h','drivers/media/pci/ddbridge/ddbridge-regs.h',g | \
	sed s,'drivers/media/dvb/ddbridge/ddbridge.h','drivers/media/pci/ddbridge/ddbridge.h',g | \
	sed s,'drivers/media/dvb/dm1105/Kconfig','drivers/media/pci/dm1105/Kconfig',g | \
	sed s,'drivers/media/dvb/dm1105/dm1105.c','drivers/media/pci/dm1105/dm1105.c',g | \
	sed s,'drivers/media/dvb/mantis/Kconfig','drivers/media/pci/mantis/Kconfig',g | \
	sed s,'drivers/media/dvb/mantis/Makefile','drivers/media/pci/mantis/Makefile',g | \
	sed s,'drivers/media/dvb/mantis/hopper_cards.c','drivers/media/pci/mantis/hopper_cards.c',g | \
	sed s,'drivers/media/dvb/mantis/hopper_vp3028.c','drivers/media/pci/mantis/hopper_vp3028.c',g | \
	sed s,'drivers/media/dvb/mantis/hopper_vp3028.h','drivers/media/pci/mantis/hopper_vp3028.h',g | \
	sed s,'drivers/media/dvb/mantis/mantis_ca.c','drivers/media/pci/mantis/mantis_ca.c',g | \
	sed s,'drivers/media/dvb/mantis/mantis_ca.h','drivers/media/pci/mantis/mantis_ca.h',g | \
	sed s,'drivers/media/dvb/mantis/mantis_cards.c','drivers/media/pci/mantis/mantis_cards.c',g | \
	sed s,'drivers/media/dvb/mantis/mantis_common.h','drivers/media/pci/mantis/mantis_common.h',g | \
	sed s,'drivers/media/dvb/mantis/mantis_core.c','drivers/media/pci/mantis/mantis_core.c',g | \
	sed s,'drivers/media/dvb/mantis/mantis_core.h','drivers/media/pci/mantis/mantis_core.h',g | \
	sed s,'drivers/media/dvb/mantis/mantis_dma.c','drivers/media/pci/mantis/mantis_dma.c',g | \
	sed s,'drivers/media/dvb/mantis/mantis_dma.h','drivers/media/pci/mantis/mantis_dma.h',g | \
	sed s,'drivers/media/dvb/mantis/mantis_dvb.c','drivers/media/pci/mantis/mantis_dvb.c',g | \
	sed s,'drivers/media/dvb/mantis/mantis_dvb.h','drivers/media/pci/mantis/mantis_dvb.h',g | \
	sed s,'drivers/media/dvb/mantis/mantis_evm.c','drivers/media/pci/mantis/mantis_evm.c',g | \
	sed s,'drivers/media/dvb/mantis/mantis_hif.c','drivers/media/pci/mantis/mantis_hif.c',g | \
	sed s,'drivers/media/dvb/mantis/mantis_hif.h','drivers/media/pci/mantis/mantis_hif.h',g | \
	sed s,'drivers/media/dvb/mantis/mantis_i2c.c','drivers/media/pci/mantis/mantis_i2c.c',g | \
	sed s,'drivers/media/dvb/mantis/mantis_i2c.h','drivers/media/pci/mantis/mantis_i2c.h',g | \
	sed s,'drivers/media/dvb/mantis/mantis_input.c','drivers/media/pci/mantis/mantis_input.c',g | \
	sed s,'drivers/media/dvb/mantis/mantis_ioc.c','drivers/media/pci/mantis/mantis_ioc.c',g | \
	sed s,'drivers/media/dvb/mantis/mantis_ioc.h','drivers/media/pci/mantis/mantis_ioc.h',g | \
	sed s,'drivers/media/dvb/mantis/mantis_link.h','drivers/media/pci/mantis/mantis_link.h',g | \
	sed s,'drivers/media/dvb/mantis/mantis_pci.c','drivers/media/pci/mantis/mantis_pci.c',g | \
	sed s,'drivers/media/dvb/mantis/mantis_pci.h','drivers/media/pci/mantis/mantis_pci.h',g | \
	sed s,'drivers/media/dvb/mantis/mantis_pcmcia.c','drivers/media/pci/mantis/mantis_pcmcia.c',g | \
	sed s,'drivers/media/dvb/mantis/mantis_reg.h','drivers/media/pci/mantis/mantis_reg.h',g | \
	sed s,'drivers/media/dvb/mantis/mantis_uart.c','drivers/media/pci/mantis/mantis_uart.c',g | \
	sed s,'drivers/media/dvb/mantis/mantis_uart.h','drivers/media/pci/mantis/mantis_uart.h',g | \
	sed s,'drivers/media/dvb/mantis/mantis_vp1033.c','drivers/media/pci/mantis/mantis_vp1033.c',g | \
	sed s,'drivers/media/dvb/mantis/mantis_vp1033.h','drivers/media/pci/mantis/mantis_vp1033.h',g | \
	sed s,'drivers/media/dvb/mantis/mantis_vp1034.c','drivers/media/pci/mantis/mantis_vp1034.c',g | \
	sed s,'drivers/media/dvb/mantis/mantis_vp1034.h','drivers/media/pci/mantis/mantis_vp1034.h',g | \
	sed s,'drivers/media/dvb/mantis/mantis_vp1041.c','drivers/media/pci/mantis/mantis_vp1041.c',g | \
	sed s,'drivers/media/dvb/mantis/mantis_vp1041.h','drivers/media/pci/mantis/mantis_vp1041.h',g | \
	sed s,'drivers/media/dvb/mantis/mantis_vp2033.c','drivers/media/pci/mantis/mantis_vp2033.c',g | \
	sed s,'drivers/media/dvb/mantis/mantis_vp2033.h','drivers/media/pci/mantis/mantis_vp2033.h',g | \
	sed s,'drivers/media/dvb/mantis/mantis_vp2040.c','drivers/media/pci/mantis/mantis_vp2040.c',g | \
	sed s,'drivers/media/dvb/mantis/mantis_vp2040.h','drivers/media/pci/mantis/mantis_vp2040.h',g | \
	sed s,'drivers/media/dvb/mantis/mantis_vp3028.c','drivers/media/pci/mantis/mantis_vp3028.c',g | \
	sed s,'drivers/media/dvb/mantis/mantis_vp3028.h','drivers/media/pci/mantis/mantis_vp3028.h',g | \
	sed s,'drivers/media/dvb/mantis/mantis_vp3030.c','drivers/media/pci/mantis/mantis_vp3030.c',g | \
	sed s,'drivers/media/dvb/mantis/mantis_vp3030.h','drivers/media/pci/mantis/mantis_vp3030.h',g | \
	sed s,'drivers/media/dvb/ngene/Kconfig','drivers/media/pci/ngene/Kconfig',g | \
	sed s,'drivers/media/dvb/ngene/Makefile','drivers/media/pci/ngene/Makefile',g | \
	sed s,'drivers/media/dvb/ngene/ngene-cards.c','drivers/media/pci/ngene/ngene-cards.c',g | \
	sed s,'drivers/media/dvb/ngene/ngene-core.c','drivers/media/pci/ngene/ngene-core.c',g | \
	sed s,'drivers/media/dvb/ngene/ngene-dvb.c','drivers/media/pci/ngene/ngene-dvb.c',g | \
	sed s,'drivers/media/dvb/ngene/ngene-i2c.c','drivers/media/pci/ngene/ngene-i2c.c',g | \
	sed s,'drivers/media/dvb/ngene/ngene.h','drivers/media/pci/ngene/ngene.h',g | \
	sed s,'drivers/media/dvb/pluto2/Kconfig','drivers/media/pci/pluto2/Kconfig',g | \
	sed s,'drivers/media/dvb/pluto2/pluto2.c','drivers/media/pci/pluto2/pluto2.c',g | \
	sed s,'drivers/media/dvb/pt1/Kconfig','drivers/media/pci/pt1/Kconfig',g | \
	sed s,'drivers/media/dvb/pt1/Makefile','drivers/media/pci/pt1/Makefile',g | \
	sed s,'drivers/media/dvb/pt1/pt1.c','drivers/media/pci/pt1/pt1.c',g | \
	sed s,'drivers/media/dvb/pt1/va1j5jf8007s.c','drivers/media/pci/pt1/va1j5jf8007s.c',g | \
	sed s,'drivers/media/dvb/pt1/va1j5jf8007s.h','drivers/media/pci/pt1/va1j5jf8007s.h',g | \
	sed s,'drivers/media/dvb/pt1/va1j5jf8007t.c','drivers/media/pci/pt1/va1j5jf8007t.c',g | \
	sed s,'drivers/media/dvb/pt1/va1j5jf8007t.h','drivers/media/pci/pt1/va1j5jf8007t.h',g | \
	sed s,'drivers/media/dvb/ttpci/Kconfig','drivers/media/pci/ttpci/Kconfig',g | \
	sed s,'drivers/media/dvb/ttpci/Makefile','drivers/media/pci/ttpci/Makefile',g | \
	sed s,'drivers/media/dvb/ttpci/av7110.c','drivers/media/pci/ttpci/av7110.c',g | \
	sed s,'drivers/media/dvb/ttpci/av7110.h','drivers/media/pci/ttpci/av7110.h',g | \
	sed s,'drivers/media/dvb/ttpci/av7110_av.c','drivers/media/pci/ttpci/av7110_av.c',g | \
	sed s,'drivers/media/dvb/ttpci/av7110_av.h','drivers/media/pci/ttpci/av7110_av.h',g | \
	sed s,'drivers/media/dvb/ttpci/av7110_ca.c','drivers/media/pci/ttpci/av7110_ca.c',g | \
	sed s,'drivers/media/dvb/ttpci/av7110_ca.h','drivers/media/pci/ttpci/av7110_ca.h',g | \
	sed s,'drivers/media/dvb/ttpci/av7110_hw.c','drivers/media/pci/ttpci/av7110_hw.c',g | \
	sed s,'drivers/media/dvb/ttpci/av7110_hw.h','drivers/media/pci/ttpci/av7110_hw.h',g | \
	sed s,'drivers/media/dvb/ttpci/av7110_ipack.c','drivers/media/pci/ttpci/av7110_ipack.c',g | \
	sed s,'drivers/media/dvb/ttpci/av7110_ipack.h','drivers/media/pci/ttpci/av7110_ipack.h',g | \
	sed s,'drivers/media/dvb/ttpci/av7110_ir.c','drivers/media/pci/ttpci/av7110_ir.c',g | \
	sed s,'drivers/media/dvb/ttpci/av7110_v4l.c','drivers/media/pci/ttpci/av7110_v4l.c',g | \
	sed s,'drivers/media/dvb/ttpci/budget-av.c','drivers/media/pci/ttpci/budget-av.c',g | \
	sed s,'drivers/media/dvb/ttpci/budget-ci.c','drivers/media/pci/ttpci/budget-ci.c',g | \
	sed s,'drivers/media/dvb/ttpci/budget-core.c','drivers/media/pci/ttpci/budget-core.c',g | \
	sed s,'drivers/media/dvb/ttpci/budget-patch.c','drivers/media/pci/ttpci/budget-patch.c',g | \
	sed s,'drivers/media/dvb/ttpci/budget.c','drivers/media/pci/ttpci/budget.c',g | \
	sed s,'drivers/media/dvb/ttpci/budget.h','drivers/media/pci/ttpci/budget.h',g | \
	sed s,'drivers/media/dvb/ttpci/ttpci-eeprom.c','drivers/media/pci/ttpci/ttpci-eeprom.c',g | \
	sed s,'drivers/media/dvb/ttpci/ttpci-eeprom.h','drivers/media/pci/ttpci/ttpci-eeprom.h',g | \
	sed s,'drivers/media/common/tuners/Kconfig','drivers/media/tuners/Kconfig',g | \
	sed s,'drivers/media/common/tuners/Makefile','drivers/media/tuners/Makefile',g | \
	sed s,'drivers/media/common/tuners/fc0011.c','drivers/media/tuners/fc0011.c',g | \
	sed s,'drivers/media/common/tuners/fc0011.h','drivers/media/tuners/fc0011.h',g | \
	sed s,'drivers/media/common/tuners/fc0012-priv.h','drivers/media/tuners/fc0012-priv.h',g | \
	sed s,'drivers/media/common/tuners/fc0012.c','drivers/media/tuners/fc0012.c',g | \
	sed s,'drivers/media/common/tuners/fc0012.h','drivers/media/tuners/fc0012.h',g | \
	sed s,'drivers/media/common/tuners/fc0013-priv.h','drivers/media/tuners/fc0013-priv.h',g | \
	sed s,'drivers/media/common/tuners/fc0013.c','drivers/media/tuners/fc0013.c',g | \
	sed s,'drivers/media/common/tuners/fc0013.h','drivers/media/tuners/fc0013.h',g | \
	sed s,'drivers/media/common/tuners/fc001x-common.h','drivers/media/tuners/fc001x-common.h',g | \
	sed s,'drivers/media/common/tuners/max2165.c','drivers/media/tuners/max2165.c',g | \
	sed s,'drivers/media/common/tuners/max2165.h','drivers/media/tuners/max2165.h',g | \
	sed s,'drivers/media/common/tuners/max2165_priv.h','drivers/media/tuners/max2165_priv.h',g | \
	sed s,'drivers/media/common/tuners/mc44s803.c','drivers/media/tuners/mc44s803.c',g | \
	sed s,'drivers/media/common/tuners/mc44s803.h','drivers/media/tuners/mc44s803.h',g | \
	sed s,'drivers/media/common/tuners/mc44s803_priv.h','drivers/media/tuners/mc44s803_priv.h',g | \
	sed s,'drivers/media/common/tuners/mt2060.c','drivers/media/tuners/mt2060.c',g | \
	sed s,'drivers/media/common/tuners/mt2060.h','drivers/media/tuners/mt2060.h',g | \
	sed s,'drivers/media/common/tuners/mt2060_priv.h','drivers/media/tuners/mt2060_priv.h',g | \
	sed s,'drivers/media/common/tuners/mt2063.c','drivers/media/tuners/mt2063.c',g | \
	sed s,'drivers/media/common/tuners/mt2063.h','drivers/media/tuners/mt2063.h',g | \
	sed s,'drivers/media/common/tuners/mt20xx.c','drivers/media/tuners/mt20xx.c',g | \
	sed s,'drivers/media/common/tuners/mt20xx.h','drivers/media/tuners/mt20xx.h',g | \
	sed s,'drivers/media/common/tuners/mt2131.c','drivers/media/tuners/mt2131.c',g | \
	sed s,'drivers/media/common/tuners/mt2131.h','drivers/media/tuners/mt2131.h',g | \
	sed s,'drivers/media/common/tuners/mt2131_priv.h','drivers/media/tuners/mt2131_priv.h',g | \
	sed s,'drivers/media/common/tuners/mt2266.c','drivers/media/tuners/mt2266.c',g | \
	sed s,'drivers/media/common/tuners/mt2266.h','drivers/media/tuners/mt2266.h',g | \
	sed s,'drivers/media/common/tuners/mxl5005s.c','drivers/media/tuners/mxl5005s.c',g | \
	sed s,'drivers/media/common/tuners/mxl5005s.h','drivers/media/tuners/mxl5005s.h',g | \
	sed s,'drivers/media/common/tuners/mxl5007t.c','drivers/media/tuners/mxl5007t.c',g | \
	sed s,'drivers/media/common/tuners/mxl5007t.h','drivers/media/tuners/mxl5007t.h',g | \
	sed s,'drivers/media/common/tuners/qt1010.c','drivers/media/tuners/qt1010.c',g | \
	sed s,'drivers/media/common/tuners/qt1010.h','drivers/media/tuners/qt1010.h',g | \
	sed s,'drivers/media/common/tuners/qt1010_priv.h','drivers/media/tuners/qt1010_priv.h',g | \
	sed s,'drivers/media/common/tuners/tda18212.c','drivers/media/tuners/tda18212.c',g | \
	sed s,'drivers/media/common/tuners/tda18212.h','drivers/media/tuners/tda18212.h',g | \
	sed s,'drivers/media/common/tuners/tda18218.c','drivers/media/tuners/tda18218.c',g | \
	sed s,'drivers/media/common/tuners/tda18218.h','drivers/media/tuners/tda18218.h',g | \
	sed s,'drivers/media/common/tuners/tda18218_priv.h','drivers/media/tuners/tda18218_priv.h',g | \
	sed s,'drivers/media/common/tuners/tda18271-common.c','drivers/media/tuners/tda18271-common.c',g | \
	sed s,'drivers/media/common/tuners/tda18271-fe.c','drivers/media/tuners/tda18271-fe.c',g | \
	sed s,'drivers/media/common/tuners/tda18271-maps.c','drivers/media/tuners/tda18271-maps.c',g | \
	sed s,'drivers/media/common/tuners/tda18271-priv.h','drivers/media/tuners/tda18271-priv.h',g | \
	sed s,'drivers/media/common/tuners/tda18271.h','drivers/media/tuners/tda18271.h',g | \
	sed s,'drivers/media/common/tuners/tda827x.c','drivers/media/tuners/tda827x.c',g | \
	sed s,'drivers/media/common/tuners/tda827x.h','drivers/media/tuners/tda827x.h',g | \
	sed s,'drivers/media/common/tuners/tda8290.c','drivers/media/tuners/tda8290.c',g | \
	sed s,'drivers/media/common/tuners/tda8290.h','drivers/media/tuners/tda8290.h',g | \
	sed s,'drivers/media/common/tuners/tda9887.c','drivers/media/tuners/tda9887.c',g | \
	sed s,'drivers/media/common/tuners/tda9887.h','drivers/media/tuners/tda9887.h',g | \
	sed s,'drivers/media/common/tuners/tea5761.c','drivers/media/tuners/tea5761.c',g | \
	sed s,'drivers/media/common/tuners/tea5761.h','drivers/media/tuners/tea5761.h',g | \
	sed s,'drivers/media/common/tuners/tea5767.c','drivers/media/tuners/tea5767.c',g | \
	sed s,'drivers/media/common/tuners/tea5767.h','drivers/media/tuners/tea5767.h',g | \
	sed s,'drivers/media/common/tuners/tua9001.c','drivers/media/tuners/tua9001.c',g | \
	sed s,'drivers/media/common/tuners/tua9001.h','drivers/media/tuners/tua9001.h',g | \
	sed s,'drivers/media/common/tuners/tua9001_priv.h','drivers/media/tuners/tua9001_priv.h',g | \
	sed s,'drivers/media/common/tuners/tuner-i2c.h','drivers/media/tuners/tuner-i2c.h',g | \
	sed s,'drivers/media/common/tuners/tuner-simple.c','drivers/media/tuners/tuner-simple.c',g | \
	sed s,'drivers/media/common/tuners/tuner-simple.h','drivers/media/tuners/tuner-simple.h',g | \
	sed s,'drivers/media/common/tuners/tuner-types.c','drivers/media/tuners/tuner-types.c',g | \
	sed s,'drivers/media/common/tuners/tuner-xc2028-types.h','drivers/media/tuners/tuner-xc2028-types.h',g | \
	sed s,'drivers/media/common/tuners/tuner-xc2028.c','drivers/media/tuners/tuner-xc2028.c',g | \
	sed s,'drivers/media/common/tuners/tuner-xc2028.h','drivers/media/tuners/tuner-xc2028.h',g | \
	sed s,'drivers/media/common/tuners/xc4000.c','drivers/media/tuners/xc4000.c',g | \
	sed s,'drivers/media/common/tuners/xc4000.h','drivers/media/tuners/xc4000.h',g | \
	sed s,'drivers/media/common/tuners/xc5000.c','drivers/media/tuners/xc5000.c',g | \
	sed s,'drivers/media/common/tuners/xc5000.h','drivers/media/tuners/xc5000.h',g | \
	sed s,'drivers/media/dvb/b2c2/flexcop-usb.c','drivers/media/usb/b2c2/flexcop-usb.c',g | \
	sed s,'drivers/media/dvb/b2c2/flexcop-usb.h','drivers/media/usb/b2c2/flexcop-usb.h',g | \
	sed s,'drivers/media/dvb/dvb-usb-v2/Kconfig','drivers/media/usb/dvb-usb-v2/Kconfig',g | \
	sed s,'drivers/media/dvb/dvb-usb-v2/Makefile','drivers/media/usb/dvb-usb-v2/Makefile',g | \
	sed s,'drivers/media/dvb/dvb-usb-v2/af9015.c','drivers/media/usb/dvb-usb-v2/af9015.c',g | \
	sed s,'drivers/media/dvb/dvb-usb-v2/af9015.h','drivers/media/usb/dvb-usb-v2/af9015.h',g | \
	sed s,'drivers/media/dvb/dvb-usb-v2/af9035.c','drivers/media/usb/dvb-usb-v2/af9035.c',g | \
	sed s,'drivers/media/dvb/dvb-usb-v2/af9035.h','drivers/media/usb/dvb-usb-v2/af9035.h',g | \
	sed s,'drivers/media/dvb/dvb-usb-v2/anysee.c','drivers/media/usb/dvb-usb-v2/anysee.c',g | \
	sed s,'drivers/media/dvb/dvb-usb-v2/anysee.h','drivers/media/usb/dvb-usb-v2/anysee.h',g | \
	sed s,'drivers/media/dvb/dvb-usb-v2/au6610.c','drivers/media/usb/dvb-usb-v2/au6610.c',g | \
	sed s,'drivers/media/dvb/dvb-usb-v2/au6610.h','drivers/media/usb/dvb-usb-v2/au6610.h',g | \
	sed s,'drivers/media/dvb/dvb-usb-v2/az6007.c','drivers/media/usb/dvb-usb-v2/az6007.c',g | \
	sed s,'drivers/media/dvb/dvb-usb-v2/ce6230.c','drivers/media/usb/dvb-usb-v2/ce6230.c',g | \
	sed s,'drivers/media/dvb/dvb-usb-v2/ce6230.h','drivers/media/usb/dvb-usb-v2/ce6230.h',g | \
	sed s,'drivers/media/dvb/dvb-usb-v2/cypress_firmware.c','drivers/media/usb/dvb-usb-v2/cypress_firmware.c',g | \
	sed s,'drivers/media/dvb/dvb-usb-v2/cypress_firmware.h','drivers/media/usb/dvb-usb-v2/cypress_firmware.h',g | \
	sed s,'drivers/media/dvb/dvb-usb-v2/dvb_usb.h','drivers/media/usb/dvb-usb-v2/dvb_usb.h',g | \
	sed s,'drivers/media/dvb/dvb-usb-v2/dvb_usb_common.h','drivers/media/usb/dvb-usb-v2/dvb_usb_common.h',g | \
	sed s,'drivers/media/dvb/dvb-usb-v2/dvb_usb_core.c','drivers/media/usb/dvb-usb-v2/dvb_usb_core.c',g | \
	sed s,'drivers/media/dvb/dvb-usb-v2/dvb_usb_urb.c','drivers/media/usb/dvb-usb-v2/dvb_usb_urb.c',g | \
	sed s,'drivers/media/dvb/dvb-usb-v2/ec168.c','drivers/media/usb/dvb-usb-v2/ec168.c',g | \
	sed s,'drivers/media/dvb/dvb-usb-v2/ec168.h','drivers/media/usb/dvb-usb-v2/ec168.h',g | \
	sed s,'drivers/media/dvb/dvb-usb-v2/gl861.c','drivers/media/usb/dvb-usb-v2/gl861.c',g | \
	sed s,'drivers/media/dvb/dvb-usb-v2/gl861.h','drivers/media/usb/dvb-usb-v2/gl861.h',g | \
	sed s,'drivers/media/dvb/dvb-usb-v2/it913x.c','drivers/media/usb/dvb-usb-v2/it913x.c',g | \
	sed s,'drivers/media/dvb/dvb-usb-v2/lmedm04.c','drivers/media/usb/dvb-usb-v2/lmedm04.c',g | \
	sed s,'drivers/media/dvb/dvb-usb-v2/lmedm04.h','drivers/media/usb/dvb-usb-v2/lmedm04.h',g | \
	sed s,'drivers/media/dvb/dvb-usb-v2/mxl111sf-demod.c','drivers/media/usb/dvb-usb-v2/mxl111sf-demod.c',g | \
	sed s,'drivers/media/dvb/dvb-usb-v2/mxl111sf-demod.h','drivers/media/usb/dvb-usb-v2/mxl111sf-demod.h',g | \
	sed s,'drivers/media/dvb/dvb-usb-v2/mxl111sf-gpio.c','drivers/media/usb/dvb-usb-v2/mxl111sf-gpio.c',g | \
	sed s,'drivers/media/dvb/dvb-usb-v2/mxl111sf-gpio.h','drivers/media/usb/dvb-usb-v2/mxl111sf-gpio.h',g | \
	sed s,'drivers/media/dvb/dvb-usb-v2/mxl111sf-i2c.c','drivers/media/usb/dvb-usb-v2/mxl111sf-i2c.c',g | \
	sed s,'drivers/media/dvb/dvb-usb-v2/mxl111sf-i2c.h','drivers/media/usb/dvb-usb-v2/mxl111sf-i2c.h',g | \
	sed s,'drivers/media/dvb/dvb-usb-v2/mxl111sf-phy.c','drivers/media/usb/dvb-usb-v2/mxl111sf-phy.c',g | \
	sed s,'drivers/media/dvb/dvb-usb-v2/mxl111sf-phy.h','drivers/media/usb/dvb-usb-v2/mxl111sf-phy.h',g | \
	sed s,'drivers/media/dvb/dvb-usb-v2/mxl111sf-reg.h','drivers/media/usb/dvb-usb-v2/mxl111sf-reg.h',g | \
	sed s,'drivers/media/dvb/dvb-usb-v2/mxl111sf-tuner.c','drivers/media/usb/dvb-usb-v2/mxl111sf-tuner.c',g | \
	sed s,'drivers/media/dvb/dvb-usb-v2/mxl111sf-tuner.h','drivers/media/usb/dvb-usb-v2/mxl111sf-tuner.h',g | \
	sed s,'drivers/media/dvb/dvb-usb-v2/mxl111sf.c','drivers/media/usb/dvb-usb-v2/mxl111sf.c',g | \
	sed s,'drivers/media/dvb/dvb-usb-v2/mxl111sf.h','drivers/media/usb/dvb-usb-v2/mxl111sf.h',g | \
	sed s,'drivers/media/dvb/dvb-usb-v2/rtl28xxu.c','drivers/media/usb/dvb-usb-v2/rtl28xxu.c',g | \
	sed s,'drivers/media/dvb/dvb-usb-v2/rtl28xxu.h','drivers/media/usb/dvb-usb-v2/rtl28xxu.h',g | \
	sed s,'drivers/media/dvb/dvb-usb-v2/usb_urb.c','drivers/media/usb/dvb-usb-v2/usb_urb.c',g | \
	sed s,'drivers/media/dvb/dvb-usb/Kconfig','drivers/media/usb/dvb-usb/Kconfig',g | \
	sed s,'drivers/media/dvb/dvb-usb/Makefile','drivers/media/usb/dvb-usb/Makefile',g | \
	sed s,'drivers/media/dvb/dvb-usb/a800.c','drivers/media/usb/dvb-usb/a800.c',g | \
	sed s,'drivers/media/dvb/dvb-usb/af9005-fe.c','drivers/media/usb/dvb-usb/af9005-fe.c',g | \
	sed s,'drivers/media/dvb/dvb-usb/af9005-remote.c','drivers/media/usb/dvb-usb/af9005-remote.c',g | \
	sed s,'drivers/media/dvb/dvb-usb/af9005-script.h','drivers/media/usb/dvb-usb/af9005-script.h',g | \
	sed s,'drivers/media/dvb/dvb-usb/af9005.c','drivers/media/usb/dvb-usb/af9005.c',g | \
	sed s,'drivers/media/dvb/dvb-usb/af9005.h','drivers/media/usb/dvb-usb/af9005.h',g | \
	sed s,'drivers/media/dvb/dvb-usb/az6027.c','drivers/media/usb/dvb-usb/az6027.c',g | \
	sed s,'drivers/media/dvb/dvb-usb/az6027.h','drivers/media/usb/dvb-usb/az6027.h',g | \
	sed s,'drivers/media/dvb/dvb-usb/cinergyT2-core.c','drivers/media/usb/dvb-usb/cinergyT2-core.c',g | \
	sed s,'drivers/media/dvb/dvb-usb/cinergyT2-fe.c','drivers/media/usb/dvb-usb/cinergyT2-fe.c',g | \
	sed s,'drivers/media/dvb/dvb-usb/cinergyT2.h','drivers/media/usb/dvb-usb/cinergyT2.h',g | \
	sed s,'drivers/media/dvb/dvb-usb/cxusb.c','drivers/media/usb/dvb-usb/cxusb.c',g | \
	sed s,'drivers/media/dvb/dvb-usb/cxusb.h','drivers/media/usb/dvb-usb/cxusb.h',g | \
	sed s,'drivers/media/dvb/dvb-usb/dib0700.h','drivers/media/usb/dvb-usb/dib0700.h',g | \
	sed s,'drivers/media/dvb/dvb-usb/dib0700_core.c','drivers/media/usb/dvb-usb/dib0700_core.c',g | \
	sed s,'drivers/media/dvb/dvb-usb/dib0700_devices.c','drivers/media/usb/dvb-usb/dib0700_devices.c',g | \
	sed s,'drivers/media/dvb/dvb-usb/dib07x0.h','drivers/media/usb/dvb-usb/dib07x0.h',g | \
	sed s,'drivers/media/dvb/dvb-usb/dibusb-common.c','drivers/media/usb/dvb-usb/dibusb-common.c',g | \
	sed s,'drivers/media/dvb/dvb-usb/dibusb-mb.c','drivers/media/usb/dvb-usb/dibusb-mb.c',g | \
	sed s,'drivers/media/dvb/dvb-usb/dibusb-mc.c','drivers/media/usb/dvb-usb/dibusb-mc.c',g | \
	sed s,'drivers/media/dvb/dvb-usb/dibusb.h','drivers/media/usb/dvb-usb/dibusb.h',g | \
	sed s,'drivers/media/dvb/dvb-usb/digitv.c','drivers/media/usb/dvb-usb/digitv.c',g | \
	sed s,'drivers/media/dvb/dvb-usb/digitv.h','drivers/media/usb/dvb-usb/digitv.h',g | \
	sed s,'drivers/media/dvb/dvb-usb/dtt200u-fe.c','drivers/media/usb/dvb-usb/dtt200u-fe.c',g | \
	sed s,'drivers/media/dvb/dvb-usb/dtt200u.c','drivers/media/usb/dvb-usb/dtt200u.c',g | \
	sed s,'drivers/media/dvb/dvb-usb/dtt200u.h','drivers/media/usb/dvb-usb/dtt200u.h',g | \
	sed s,'drivers/media/dvb/dvb-usb/dtv5100.c','drivers/media/usb/dvb-usb/dtv5100.c',g | \
	sed s,'drivers/media/dvb/dvb-usb/dtv5100.h','drivers/media/usb/dvb-usb/dtv5100.h',g | \
	sed s,'drivers/media/dvb/dvb-usb/dvb-usb-common.h','drivers/media/usb/dvb-usb/dvb-usb-common.h',g | \
	sed s,'drivers/media/dvb/dvb-usb/dvb-usb-dvb.c','drivers/media/usb/dvb-usb/dvb-usb-dvb.c',g | \
	sed s,'drivers/media/dvb/dvb-usb/dvb-usb-firmware.c','drivers/media/usb/dvb-usb/dvb-usb-firmware.c',g | \
	sed s,'drivers/media/dvb/dvb-usb/dvb-usb-i2c.c','drivers/media/usb/dvb-usb/dvb-usb-i2c.c',g | \
	sed s,'drivers/media/dvb/dvb-usb/dvb-usb-init.c','drivers/media/usb/dvb-usb/dvb-usb-init.c',g | \
	sed s,'drivers/media/dvb/dvb-usb/dvb-usb-remote.c','drivers/media/usb/dvb-usb/dvb-usb-remote.c',g | \
	sed s,'drivers/media/dvb/dvb-usb/dvb-usb-urb.c','drivers/media/usb/dvb-usb/dvb-usb-urb.c',g | \
	sed s,'drivers/media/dvb/dvb-usb/dvb-usb.h','drivers/media/usb/dvb-usb/dvb-usb.h',g | \
	sed s,'drivers/media/dvb/dvb-usb/dvb_usb_dvb.c','drivers/media/usb/dvb-usb/dvb_usb_dvb.c',g | \
	sed s,'drivers/media/dvb/dvb-usb/dvb_usb_remote.c','drivers/media/usb/dvb-usb/dvb_usb_remote.c',g | \
	sed s,'drivers/media/dvb/dvb-usb/dw2102.c','drivers/media/usb/dvb-usb/dw2102.c',g | \
	sed s,'drivers/media/dvb/dvb-usb/dw2102.h','drivers/media/usb/dvb-usb/dw2102.h',g | \
	sed s,'drivers/media/dvb/dvb-usb/friio-fe.c','drivers/media/usb/dvb-usb/friio-fe.c',g | \
	sed s,'drivers/media/dvb/dvb-usb/friio.c','drivers/media/usb/dvb-usb/friio.c',g | \
	sed s,'drivers/media/dvb/dvb-usb/friio.h','drivers/media/usb/dvb-usb/friio.h',g | \
	sed s,'drivers/media/dvb/dvb-usb/gp8psk-fe.c','drivers/media/usb/dvb-usb/gp8psk-fe.c',g | \
	sed s,'drivers/media/dvb/dvb-usb/gp8psk.c','drivers/media/usb/dvb-usb/gp8psk.c',g | \
	sed s,'drivers/media/dvb/dvb-usb/gp8psk.h','drivers/media/usb/dvb-usb/gp8psk.h',g | \
	sed s,'drivers/media/dvb/dvb-usb/m920x.c','drivers/media/usb/dvb-usb/m920x.c',g | \
	sed s,'drivers/media/dvb/dvb-usb/m920x.h','drivers/media/usb/dvb-usb/m920x.h',g | \
	sed s,'drivers/media/dvb/dvb-usb/nova-t-usb2.c','drivers/media/usb/dvb-usb/nova-t-usb2.c',g | \
	sed s,'drivers/media/dvb/dvb-usb/opera1.c','drivers/media/usb/dvb-usb/opera1.c',g | \
	sed s,'drivers/media/dvb/dvb-usb/pctv452e.c','drivers/media/usb/dvb-usb/pctv452e.c',g | \
	sed s,'drivers/media/dvb/dvb-usb/technisat-usb2.c','drivers/media/usb/dvb-usb/technisat-usb2.c',g | \
	sed s,'drivers/media/dvb/dvb-usb/ttusb2.c','drivers/media/usb/dvb-usb/ttusb2.c',g | \
	sed s,'drivers/media/dvb/dvb-usb/ttusb2.h','drivers/media/usb/dvb-usb/ttusb2.h',g | \
	sed s,'drivers/media/dvb/dvb-usb/umt-010.c','drivers/media/usb/dvb-usb/umt-010.c',g | \
	sed s,'drivers/media/dvb/dvb-usb/usb-urb.c','drivers/media/usb/dvb-usb/usb-urb.c',g | \
	sed s,'drivers/media/dvb/dvb-usb/vp702x-fe.c','drivers/media/usb/dvb-usb/vp702x-fe.c',g | \
	sed s,'drivers/media/dvb/dvb-usb/vp702x.c','drivers/media/usb/dvb-usb/vp702x.c',g | \
	sed s,'drivers/media/dvb/dvb-usb/vp702x.h','drivers/media/usb/dvb-usb/vp702x.h',g | \
	sed s,'drivers/media/dvb/dvb-usb/vp7045-fe.c','drivers/media/usb/dvb-usb/vp7045-fe.c',g | \
	sed s,'drivers/media/dvb/dvb-usb/vp7045.c','drivers/media/usb/dvb-usb/vp7045.c',g | \
	sed s,'drivers/media/dvb/dvb-usb/vp7045.h','drivers/media/usb/dvb-usb/vp7045.h',g | \
	sed s,'drivers/media/dvb/siano/smsusb.c','drivers/media/usb/siano/smsusb.c',g | \
	sed s,'drivers/media/dvb/ttusb-budget/Kconfig','drivers/media/usb/ttusb-budget/Kconfig',g | \
	sed s,'drivers/media/dvb/ttusb-budget/dvb-ttusb-budget.c','drivers/media/usb/ttusb-budget/dvb-ttusb-budget.c',g | \
	sed s,'drivers/media/dvb/ttusb-dec/Kconfig','drivers/media/usb/ttusb-dec/Kconfig',g | \
	sed s,'drivers/media/dvb/ttusb-dec/Makefile','drivers/media/usb/ttusb-dec/Makefile',g | \
	sed s,'drivers/media/dvb/ttusb-dec/ttusb_dec.c','drivers/media/usb/ttusb-dec/ttusb_dec.c',g | \
	sed s,'drivers/media/dvb/ttusb-dec/ttusbdecfe.c','drivers/media/usb/ttusb-dec/ttusbdecfe.c',g | \
	sed s,'drivers/media/dvb/ttusb-dec/ttusbdecfe.h','drivers/media/usb/ttusb-dec/ttusbdecfe.h',g | \
	sed s,'drivers/media/video/tuner-core.c','drivers/media/v4l2-core/tuner-core.c',g | \
	sed s,'drivers/media/video/v4l2-common.c','drivers/media/v4l2-core/v4l2-common.c',g | \
	sed s,'drivers/media/video/v4l2-compat-ioctl32.c','drivers/media/v4l2-core/v4l2-compat-ioctl32.c',g | \
	sed s,'drivers/media/video/v4l2-ctrls.c','drivers/media/v4l2-core/v4l2-ctrls.c',g | \
	sed s,'drivers/media/video/v4l2-dev.c','drivers/media/v4l2-core/v4l2-dev.c',g | \
	sed s,'drivers/media/video/v4l2-device.c','drivers/media/v4l2-core/v4l2-device.c',g | \
	sed s,'drivers/media/video/v4l2-event.c','drivers/media/v4l2-core/v4l2-event.c',g | \
	sed s,'drivers/media/video/v4l2-fh.c','drivers/media/v4l2-core/v4l2-fh.c',g | \
	sed s,'drivers/media/video/v4l2-int-device.c','drivers/media/v4l2-core/v4l2-int-device.c',g | \
	sed s,'drivers/media/video/v4l2-ioctl.c','drivers/media/v4l2-core/v4l2-ioctl.c',g | \
	sed s,'drivers/media/video/v4l2-mem2mem.c','drivers/media/v4l2-core/v4l2-mem2mem.c',g | \
	sed s,'drivers/media/video/v4l2-subdev.c','drivers/media/v4l2-core/v4l2-subdev.c',g | \
	sed s,'drivers/media/video/videobuf-core.c','drivers/media/v4l2-core/videobuf-core.c',g | \
	sed s,'drivers/media/video/videobuf-dma-contig.c','drivers/media/v4l2-core/videobuf-dma-contig.c',g | \
	sed s,'drivers/media/video/videobuf-dma-sg.c','drivers/media/v4l2-core/videobuf-dma-sg.c',g | \
	sed s,'drivers/media/video/videobuf-dvb.c','drivers/media/v4l2-core/videobuf-dvb.c',g | \
	sed s,'drivers/media/video/videobuf-vmalloc.c','drivers/media/v4l2-core/videobuf-vmalloc.c',g | \
	sed s,'drivers/media/video/videobuf2-core.c','drivers/media/v4l2-core/videobuf2-core.c',g | \
	sed s,'drivers/media/video/videobuf2-dma-contig.c','drivers/media/v4l2-core/videobuf2-dma-contig.c',g | \
	sed s,'drivers/media/video/videobuf2-dma-sg.c','drivers/media/v4l2-core/videobuf2-dma-sg.c',g | \
	sed s,'drivers/media/video/videobuf2-memops.c','drivers/media/v4l2-core/videobuf2-memops.c',g | \
	sed s,'drivers/media/video/videobuf2-vmalloc.c','drivers/media/v4l2-core/videobuf2-vmalloc.c',g >$1 && \
echo -e "old patch stored as "$OLD"\n$1 rewrote."
